export const top50Books = [
  { gutenbergId: 84, title: 'Frankenstein', author: 'Mary Shelley' },
  { gutenbergId: 1342, title: 'Pride and Prejudice', author: 'Jane Austen' },
  { gutenbergId: 11, title: "Alice's Adventures in Wonderland", author: 'Lewis Carroll' },
  { gutenbergId: 1661, title: 'The Adventures of Sherlock Holmes', author: 'Arthur Conan Doyle' },
  { gutenbergId: 98, title: 'A Tale of Two Cities', author: 'Charles Dickens' },
  { gutenbergId: 2701, title: 'Moby Dick', author: 'Herman Melville' },
  { gutenbergId: 74, title: 'The Adventures of Tom Sawyer', author: 'Mark Twain' },
  { gutenbergId: 76, title: 'Adventures of Huckleberry Finn', author: 'Mark Twain' },
  { gutenbergId: 345, title: 'Dracula', author: 'Bram Stoker' },
  { gutenbergId: 1080, title: 'A Modest Proposal', author: 'Jonathan Swift' },
  { gutenbergId: 1952, title: 'The Yellow Wallpaper', author: 'Charlotte Perkins Gilman' },
  { gutenbergId: 1400, title: 'Great Expectations', author: 'Charles Dickens' },
  { gutenbergId: 4300, title: 'Ulysses', author: 'James Joyce' },
  { gutenbergId: 64317, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald' },
  { gutenbergId: 2554, title: 'Crime and Punishment', author: 'Fyodor Dostoevsky' },
  { gutenbergId: 46, title: 'A Christmas Carol', author: 'Charles Dickens' },
  { gutenbergId: 16328, title: 'Beowulf', author: 'Unknown' },
  { gutenbergId: 5200, title: 'Metamorphosis', author: 'Franz Kafka' },
  { gutenbergId: 27827, title: 'The Kama Sutra of Vatsyayana', author: 'Vatsyayana' },
  { gutenbergId: 174, title: 'The Picture of Dorian Gray', author: 'Oscar Wilde' },
  { gutenbergId: 2591, title: 'Grimms Fairy Tales', author: 'Jacob Grimm and Wilhelm Grimm' },
  { gutenbergId: 25344, title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne' },
  { gutenbergId: 844, title: 'The Importance of Being Earnest', author: 'Oscar Wilde' },
  { gutenbergId: 5827, title: 'The Problems of Philosophy', author: 'Bertrand Russell' },
  { gutenbergId: 215, title: 'The Call of the Wild', author: 'Jack London' },
  { gutenbergId: 1184, title: 'The Count of Monte Cristo', author: 'Alexandre Dumas' },
  { gutenbergId: 16, title: 'Peter Pan', author: 'J. M. Barrie' },
  { gutenbergId: 55, title: 'The Wonderful Wizard of Oz', author: 'L. Frank Baum' },
  { gutenbergId: 1260, title: 'Jane Eyre', author: 'Charlotte Brontë' },
  { gutenbergId: 161, title: 'Sense and Sensibility', author: 'Jane Austen' },
  { gutenbergId: 158, title: 'Emma', author: 'Jane Austen' },
  { gutenbergId: 28054, title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky' },
  { gutenbergId: 996, title: 'Don Quixote', author: 'Miguel de Cervantes' },
  { gutenbergId: 1497, title: 'The Republic', author: 'Plato' },
  { gutenbergId: 1727, title: 'The Odyssey', author: 'Homer' },
  { gutenbergId: 6130, title: 'The Iliad', author: 'Homer' },
  { gutenbergId: 2542, title: 'A Doll’s House', author: 'Henrik Ibsen' },
  { gutenbergId: 1998, title: 'Thus Spake Zarathustra', author: 'Friedrich Nietzsche' },
  { gutenbergId: 1250, title: 'Anthem', author: 'Ayn Rand' },
  { gutenbergId: 768, title: 'Wuthering Heights', author: 'Emily Brontë' },
  { gutenbergId: 2814, title: 'Dubliners', author: 'James Joyce' },
  { gutenbergId: 36, title: 'The War of the Worlds', author: 'H. G. Wells' },
  { gutenbergId: 35, title: 'The Time Machine', author: 'H. G. Wells' },
  { gutenbergId: 1399, title: 'Anna Karenina', author: 'Leo Tolstoy' },
  { gutenbergId: 829, title: 'Gulliver’s Travels', author: 'Jonathan Swift' },
  { gutenbergId: 514, title: 'Little Women', author: 'Louisa May Alcott' },
  { gutenbergId: 41, title: 'The Legend of Sleepy Hollow', author: 'Washington Irving' },
  { gutenbergId: 6593, title: 'History of Tom Jones, a Foundling', author: 'Henry Fielding' },
  { gutenbergId: 2852, title: 'The Hound of the Baskervilles', author: 'Arthur Conan Doyle' },
  { gutenbergId: 219, title: 'Heart of Darkness', author: 'Joseph Conrad' },
];
